#!/bin/bash
# quick_commands.sh - Comandos rápidos de referencia
# No ejecutar directamente, solo copiar/pegar según necesites

echo "=== Quick Reference Commands for HPCCasoEstudio3 ==="
echo ""
echo "SETUP & COMPILATION"
echo "-------------------"
echo "cd ~/HPCCasoEstudio3"
echo "make clean && make"
echo "ls -lh bin/"
echo ""

echo "VERIFY MPI"
echo "----------"
echo "which mpicc"
echo "mpirun --hostfile hostfile -np 6 hostname"
echo ""

echo "DEPLOY TO WORKERS"
echo "-----------------"
echo "./scripts/deploy.sh"
echo ""

echo "QUICK TESTS (copy/paste these one by one)"
echo "------------------------------------------"
echo "# Sequential baseline"
echo "mpirun -np 2 ./bin/matrix_mpi_sequential 256"
echo ""
echo "# Rowwise with 2, 4, 6 processes"
echo "mpirun --hostfile hostfile -np 2 ./bin/matrix_mpi_rowwise 512"
echo "mpirun --hostfile hostfile -np 4 ./bin/matrix_mpi_rowwise 512"
echo "mpirun --hostfile hostfile -np 6 ./bin/matrix_mpi_rowwise 1024"
echo ""
echo "# Broadcast optimized"
echo "mpirun --hostfile hostfile -np 6 ./bin/matrix_mpi_broadcast 1024"
echo ""
echo "# Non-blocking"
echo "mpirun --hostfile hostfile -np 6 ./bin/matrix_mpi_nonblocking 1024"
echo ""

echo "FULL BENCHMARKS"
echo "---------------"
echo "./scripts/run_benchmarks.sh"
echo "# Wait 10-15 minutes..."
echo "cat results/benchmarks.csv"
echo ""

echo "MONITORING (run in separate terminals)"
echo "---------------------------------------"
echo "# Memory on head node"
echo "watch -n1 'free -h'"
echo ""
echo "# Memory on workers"
echo "ssh worker1 'watch -n1 free -h'"
echo "ssh worker2 'watch -n1 free -h'"
echo ""
echo "# Running processes"
echo "watch -n1 'ps aux | grep matrix_mpi | grep -v grep'"
echo ""

echo "ANALYSIS"
echo "--------"
echo "python3 scripts/analyze_results.py"
echo "ls -lh results/"
echo "cat results/summary_report.txt"
echo ""

echo "CLEANUP"
echo "-------"
echo "# Kill all MPI processes"
echo "killall -9 matrix_mpi_sequential matrix_mpi_rowwise matrix_mpi_broadcast matrix_mpi_nonblocking"
echo ""
echo "# Clean build"
echo "make clean"
echo ""
echo "# Clean results"
echo "rm -f results/*.csv results/*.png results/*.txt"
echo ""

echo "TROUBLESHOOTING"
echo "---------------"
echo "# Check MPI version"
echo "mpirun --version"
echo ""
echo "# Test basic MPI"
echo "mpirun -np 2 hostname"
echo ""
echo "# Verbose MPI (debug)"
echo "mpirun --mca btl_base_verbose 30 --hostfile hostfile -np 2 ./bin/matrix_mpi_sequential 128"
echo ""
echo "# Check connectivity"
echo "ping -c 3 worker1"
echo "ssh worker1 hostname"
echo ""
echo "# Memory check"
echo "free -h"
echo "ssh worker1 free -h"
echo "ssh worker2 free -h"
echo ""

echo "DOWNLOAD RESULTS TO LOCAL"
echo "-------------------------"
echo "# Run from LOCAL machine:"
echo "scp -i ~/.ssh/your-key.pem -r ubuntu@18.224.187.40:~/HPCCasoEstudio3/results ./results_aws"
echo ""

echo "=== End of Quick Commands ==="
