#!/bin/bash
# INSTRUCCIONES ESPECÍFICAS PARA TU CLUSTER

echo "=== Configuración de tu Cluster AWS ==="
echo ""
echo "IPs configuradas:"
echo "  Head node:  172.31.28.209 (slots=2)"
echo "  Worker 1:   172.31.18.36  (slots=2)"
echo "  Worker 2:   172.31.16.182 (slots=2)"
echo "  Total:      6 slots"
echo ""

echo "=== Pasos Rápidos ==="
echo ""
echo "1. COMPRIMIR Y TRANSFERIR"
echo "-------------------------"
echo "cd /Users/isaacpachon/Desktop/Dev/UTP/HPC"
echo "tar -czf HPCCasoEstudio3.tar.gz HPCCasoEstudio3/"
echo "scp HPCCasoEstudio3.tar.gz ubuntu@18.224.187.40:~/"
echo ""

echo "2. EN EL HEAD NODE (18.224.187.40)"
echo "-----------------------------------"
echo "# Conectar"
echo "ssh ubuntu@18.224.187.40"
echo ""
echo "# Extraer"
echo "tar -xzf HPCCasoEstudio3.tar.gz"
echo "cd HPCCasoEstudio3"
echo ""
echo "# El hostfile YA está configurado con tus IPs"
echo "cat hostfile"
echo ""

echo "3. COMPILAR"
echo "-----------"
echo "make clean"
echo "make"
echo "ls -lh bin/"
echo ""

echo "4. DESPLEGAR A WORKERS"
echo "----------------------"
echo "chmod +x scripts/deploy.sh"
echo "./scripts/deploy.sh"
echo "# Script desplegará a 172.31.18.36 y 172.31.16.182"
echo ""

echo "5. TEST INICIAL"
echo "---------------"
echo "# Test local (2 procesos en head)"
echo "mpirun -np 2 ./bin/matrix_mpi_sequential 256"
echo ""
echo "# Test distribuido (6 procesos en cluster)"
echo "mpirun --hostfile hostfile -np 6 hostname"
echo "# Deberías ver 6 líneas con las IPs"
echo ""
echo "mpirun --hostfile hostfile -np 6 ./bin/matrix_mpi_rowwise 512"
echo ""

echo "6. BENCHMARKS COMPLETOS"
echo "-----------------------"
echo "chmod +x scripts/run_benchmarks.sh"
echo "./scripts/run_benchmarks.sh"
echo "# Esperará ~10-15 minutos"
echo ""

echo "7. ANÁLISIS"
echo "-----------"
echo "# Opción A: En el cluster (si tienes Python + librerías)"
echo "python3 scripts/analyze_results.py"
echo ""
echo "# Opción B: Descargar a local"
echo "# En tu Mac:"
echo "scp -r ubuntu@18.224.187.40:~/HPCCasoEstudio3/results ./results_aws"
echo "cd results_aws"
echo "python3 ../HPCCasoEstudio3/scripts/analyze_results.py"
echo ""

echo "=== Verificaciones Importantes ==="
echo ""
echo "ANTES de deploy.sh, verificar conectividad SSH:"
echo "  ssh 172.31.18.36 hostname"
echo "  ssh 172.31.16.182 hostname"
echo ""
echo "Si falla SSH, verificar:"
echo "  - SSH keys configuradas sin password"
echo "  - Security groups permiten tráfico interno"
echo "  - /etc/hosts tiene las IPs (opcional)"
echo ""

echo "NOTA: El hostfile usa IPs directas (no nombres):"
echo "  172.31.28.209 slots=2"
echo "  172.31.18.36 slots=2"
echo "  172.31.16.182 slots=2"
echo ""
echo "Esto coincide con tu mpi_hosts actual ✓"
echo ""

echo "=== Comandos de Troubleshooting ==="
echo ""
echo "# Ver memoria disponible"
echo "free -h"
echo "ssh 172.31.18.36 free -h"
echo "ssh 172.31.16.182 free -h"
echo ""
echo "# Verificar MPI"
echo "mpirun --hostfile hostfile -np 6 hostname"
echo ""
echo "# Matar procesos si se cuelgan"
echo "killall -9 matrix_mpi_rowwise"
echo "ssh 172.31.18.36 'killall -9 matrix_mpi_rowwise'"
echo "ssh 172.31.16.182 'killall -9 matrix_mpi_rowwise'"
echo ""

echo "¡Todo configurado para tu cluster! 🚀"
